# Generated by Django 5.0.1 on 2025-04-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
